# Source: hdfs/charts/hdfs-datanode-k8s/templates/datanode-daemonset.yaml
# Deleting a daemonset may need some trick. See
# https://github.com/kubernetes/kubernetes/issues/33245#issuecomment-261250489
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-hdfs-datanode
  labels:
    app: hdfs-datanode
    release: my-hdfs-datanode
spec:
  selector:
    matchLabels:
      app: hdfs-datanode
      release: my-hdfs-datanode
  template:
    metadata:
      labels:
        app: hdfs-datanode
        release: my-hdfs-datanode
    spec:
#      nodeSelector:
#        hdfs-role: datanode
#      securityContext:
#        runAsUser: 0
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
#      initContainers:
#        - name: fix-permissions
#          image: busybox
#          command: [ "sh", "-c", "chown -R 10000:1000 /hadoop/dfs/data0" ]
#          volumeMounts:
#            - name: hdfs-data-0
#              mountPath: /hadoop/dfs/data0
      initContainers:
        - name: init-hadoop-common
          image: dtweave/hadoop-common:v3.3.4
          imagePullPolicy: IfNotPresent
          command: [ 'sh', '-c', 'cp -r /opt/software/hadoop-3.3.4/* /opt/hadoop-3.3.4' ]
          volumeMounts:
            - name: hadoop-common
              mountPath: /opt/hadoop-3.3.4
      containers:
        - name: datanode
          image: dtweave/hdfs-datanode:v3.3.4-1.0.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            runAsUser: 10000
          volumeMounts:
            - name: hdfs-config
              mountPath: /hadoop/conf
              readOnly: true
            - name: hadoop-common
              mountPath: /opt/hadoop-3.3.4
            - name: hdfs-data-0
              mountPath: /hadoop/dfs/data0
              subPath: data0
#            - name: hdfs-data-1
#              mountPath: /hadoop/dfs/data1
#              subPath: data1
#            - name: hdfs-data-2
#              mountPath: /hadoop/dfs/data2
#              subPath: data2
      restartPolicy: Always
      volumes:
        - name: hdfs-config
          configMap:
            name: my-hdfs-config
        - name: hadoop-common
          emptyDir: {}
        - name: hdfs-data-0
          hostPath:
            path: /tmp/sda0/
#        - name: hdfs-data-1
#          hostPath:
#            path: /my-mnt/sda1/hdfs-data
#        - name: hdfs-data-2
#          hostPath:
#            path: /my-mnt/sda2/hdfs-data