---
# Source: hdfs/charts/hdfs-journalnode-k8s/templates/journalnode-statefulset.yaml
# A headless service to create DNS records.
apiVersion: v1
kind: Service
metadata:
  name: my-hdfs-journalnode
  labels:
    app: hdfs-journalnode
    release: my-hdfs-journalnode
  annotations:
    # TODO: Deprecated. Replace tolerate-unready-endpoints with
    # v1.Service.PublishNotReadyAddresses.
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - port: 8485
      name: jn
    - port: 8480
      name: http
  clusterIP: None
  selector:
    app: hdfs-journalnode
    release: my-hdfs-journalnode
---
# Source: hdfs/charts/hdfs-journalnode-k8s/templates/journalnode-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-hdfs-journalnode
  labels:
    app: hdfs-journalnode
    release: my-hdfs-journalnode
spec:
  serviceName: my-hdfs-journalnode
  replicas: 3
  selector:
    matchLabels:
      app: hdfs-journalnode
      release: my-hdfs-journalnode
  template:
    metadata:
      labels:
        app: hdfs-journalnode
        release: my-hdfs-journalnode
    spec:
      securityContext:
        fsGroupChangePolicy: Always
        fsGroup: 1000
      initContainers:
        - name: init-hadoop-common
          image: dtweave/hadoop-common:v3.3.4
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
          args:
            - -ec
            - |
              cp -r /opt/software/hadoop-3.3.4/* /opt/hadoop-3.3.4
              mkdir -p /hadoop/dfs/journal
              chown -R 10000:1000 /hadoop/dfs/journal
              chown -R 10000:1000 /opt/hadoop-3.3.4
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: hadoop-common
              mountPath: /opt/hadoop-3.3.4
            - name: edits-dir
              mountPath: /hadoop/dfs/journal
              subPath: journal
      containers:
        - name: hdfs-journalnode
          image: dtweave/hdfs-journalnode:v3.3.4-1.0.0
          securityContext:
            runAsUser: 10000
            runAsGroup: 1000
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
            seccompProfile:
              type: "RuntimeDefault"
          ports:
            - containerPort: 8485
              name: jn
            - containerPort: 8480
              name: http
          env:
            - name: WAIT_ZK_TO_READY
              value: "false"
          volumeMounts:
            - name: edits-dir
              mountPath: /hadoop/dfs/journal
              subPath: journal
            - name: hdfs-config
              mountPath: /hadoop/conf
              readOnly: true
            - name: hadoop-common
              mountPath: /opt/hadoop-3.3.4
      restartPolicy: Always
      volumes:
        - name: hdfs-config
          configMap:
            name: my-hdfs-config
        - name: hadoop-common
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: edits-dir
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "10Gi"
