---
apiVersion: v1
kind: Service
metadata:
  name: my-hdfs-namenode
  labels:
    app: hdfs-namenode
    release: my-hdfs-namenode
  annotations:
    # TODO: Deprecated. Replace tolerate-unready-endpoints with
    # v1.Service.PublishNotReadyAddresses.
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - port: 8020
      name: fs
    - port: 9870
      name: http
  clusterIP: None
  selector:
    app: hdfs-namenode
    release: my-hdfs-namenode
---
# Source: hdfs/charts/hdfs-namenode-k8s/templates/namenode-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-hdfs-namenode
  labels:
    app: hdfs-namenode
    release: my-hdfs-namenode
spec:
  serviceName: my-hdfs-namenode
  replicas: 2
  selector:
    matchLabels:
      app: hdfs-namenode
      release: my-hdfs-namenode
  template:
    metadata:
      labels:
        app: hdfs-namenode
        release: my-hdfs-namenode
    spec:
      initContainers:
        - name: init-hadoop-common
          image: dtweave/hadoop-common:v3.3.4
          imagePullPolicy: IfNotPresent
          command: [ 'sh', '-c', 'cp -r /opt/software/hadoop-3.3.4/* /opt/hadoop-3.3.4' ]
          volumeMounts:
            - name: hadoop-common
              mountPath: /opt/hadoop-3.3.4
      containers:
        # TODO: Support hadoop version as option.
        - name: hdfs-namenode
          image: dtweave/hdfs-namenode:v3.3.4-1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: CURRENT_POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 8020
              name: fs
            - containerPort: 9870
              name: http
          securityContext:
            runAsUser: 10000
          volumeMounts:
            - name: metadata-dir
              mountPath: /hadoop/dfs/metadata
              subPath: metadata
            - name: hdfs-config
              mountPath: /hadoop/conf
              readOnly: true
            - name: hadoop-common
              mountPath: /opt/hadoop-3.3.4
      restartPolicy: Always
      volumes:
        - name: hdfs-config
          configMap:
            name: my-hdfs-config
        - name: hadoop-common
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: metadata-dir
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "10Gi"
---