---
apiVersion: v1
kind: Service
metadata:
  name: web-ui
spec:
  selector:
    app: hdfs-namenode
    release: my-hdfs-namenode
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9870
      targetPort: 9870

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: hadoop.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-ui
                port:
                  number: 9870
