apiVersion: v1
kind: Service
metadata:
  name: zk-svc
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
      name: zk-client
    - port: 2888
      name: follower
    - port: 3888
      name: election
  clusterIP: None
  selector:
    app: zookeeper
  publishNotReadyAddresses: true